version: '3.7'
services:
  
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: iu-compro-php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - iu-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8012:80" 
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - iu-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: iu-db
    restart: unless-stopped
    tty: true
    ports:
      - "3367:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_RPASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER : ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker-compose/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - iu-network

#Docker Networks
networks:
  iu-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local